name: Simple Nodejs API Test

on: 
  push:
    branches:
      - release

jobs:
  nodejs-api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Post new user
        run : |
          curl -X POST https://nodejs-app-alpha.herokuapp.com/user \
          -H "Content-Type: application/json" \
          -d '{"name":"Lessa","password":"123454567","passwordConfirmation":"123454567","email": "lessa@driven.com"}'
      - name: Get all users
        run :  curl https://nodejs-app-alpha.herokuapp.com/users
      - name: Get nodejs version
        run: node -v
      - name: Open Pull Request
        run : |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/pulls \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          -d '{"title":"Add new features","body":"it successfully passes all the tests","head":"release","base":"main"}'
    
    
   
    


